In [1]:
import pandas as pd  # pandas 패키지 불러오기 
pd.set_option('display.max_columns', None)  # 데이터 프레임 모든 열 표시

import matplotlib.pyplot as plt  # matplotlib 패키지 불러오기
import seaborn as sns      # seaborn 패키지 불러오기 
import math                # 원할한 함수 사용을 위해 math 패키지 불러오기 
import warnings       # 경고표시 나오지 않게 하는 warnings 패키지 불러오기 
warnings.filterwarnings(action='ignore')     # 경고표시 설정 : "무시"

# 한글 설정
from matplotlib import rc   
plt.rcParams['axes.unicode_minus'] = False   # 그래프 한글 설정을 위해 matplotlib에서 rc 불러오기 (한글 깨짐 현상을 막아줌)

# 폰트설정(시스템에 따라 다르게 설정 window = malgun, mac = AppleGothic)
import platform
if platform.system() == 'Windows':
    path = "c:/Windows/Fonts/malgun.ttf"
    font_name = font_manager.FontProperties(fname=path).get_name()
    rc('font', family=font_name)
elif platform.system() == 'Darwin':
    rc('font', family='AppleGothic')
elif platform.system() == 'Linux':
    rc('font', family='NanumBarunGothic')
else:
    print('Unknown system... sorry~~')

In [2]:
kaida = pd.read_csv('datas/kaida.csv')
kaida

                brand            model  value sales_type  age month  year
0                 BMW    218dGranCoupe      0      개인-남자  ~19    1월  2021
1                 BMW              520      1      개인-남자  ~19    1월  2021
2             Bentley  ContinentalGTV8      0      개인-남자  ~19    1월  2021
3               Honda       CR-VHybrid      0      개인-남자  ~19    1월  2021
4       Mercedes-Benz             E250      1      개인-남자  ~19    1월  2021
...               ...              ...    ...        ...  ...   ...   ...
271951            BMW           XC70D5      0         법인    -   12월  2016
271952            BMW        XC90D5AWD     34         법인    -   12월  2016
271953            BMW        XC90T6AWD     11         법인    -   12월  2016
271954            BMW        XC90T8AWD      3         법인    -   12월  2016
271955            BMW            Total  6,975         법인    -   12월  2016

[271956 rows x 7 columns]

In [3]:
kaida.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271956 entries, 0 to 271955
Data columns (total 7 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   brand       271956 non-null  object
 1   model       271956 non-null  object
 2   value       271956 non-null  object
 3   sales_type  271956 non-null  object
 4   age         271956 non-null  object
 5   month       271956 non-null  object
 6   year        271956 non-null  int64
dtypes: int64(1), object(6)
memory usage: 14.5+ MB

In [4]:
kaida['sales_type'] = kaida['sales_type'].str.replace(' 법인','법인') 
kaida = kaida.drop_duplicates()
kaida['value'] = kaida['value'].str.replace(',','')
kaida['value'] = kaida['value'].astype(int)
kaida['month'] = kaida['month'].str.replace('월','')
kaida['month'] = kaida['month'].astype(int)
kaida['year'] = kaida['year'].astype(object)
kaida = kaida[kaida['model']!='Total']

# age컬럼 이름 변경
kaida['age'] = kaida['age'].str.replace('~19','10대')
kaida['age'] = kaida['age'].str.replace('20~29','20대')
kaida['age'] = kaida['age'].str.replace('30~39','30대')
kaida['age'] = kaida['age'].str.replace('40~49','40대')
kaida['age'] = kaida['age'].str.replace('50~59','50대')
kaida['age'] = kaida['age'].str.replace('60~69','60대')
kaida['age'] = kaida['age'].str.replace('70~','70대 이상')
kaida['age'] = kaida['age'].str.replace('-','법인')

In [5]:
kaida['year'] = pd.to_datetime(kaida['year'], format="%Y", errors='raise')
kaida['month'] = pd.to_datetime(kaida['month'], format="%m", errors='raise')

kaida['year'] = kaida['year'].dt.year
kaida['month'] = kaida["month"].dt.month

kaida.sort_values(["year", "month"], inplace=True)

kaida['date'] = kaida['year'].astype(str) + "-" + kaida['month'].astype(str)

In [6]:
kaida = kaida[["date", "year", "month", "brand", "model", "value", "sales_type", "age"]].reset_index()
# 필요없는 컬럼 'index' 제거 
kaida.drop(['index'], axis=1, inplace=True)
kaida

,date,year,month,brand,model,value,sales_type,age
0,2016-1,2016,1,BMW,A335TDI,35,개인-남자,10대
1,2016-1,2016,1,BMW,A335TFSI,1,개인-남자,10대
2,2016-1,2016,1,Bentley,A3Sportback35TDI,22,개인-남자,10대
3,2016-1,2016,1,Honda,A3Sportbacke-tron,0,개인-남자,10대
4,2016-1,2016,1,Mercedes-Benz,A430TDI,54,개인-남자,10대
...,...,...,...,...,...,...,...,...
240043,2021-12,2021,12,Maserati,XC60B5AWD,0,법인,법인
240044,2021-12,2021,12,Maserati,XC60B6AWD,0,법인,법인
240045,2021-12,2021,12,Maserati,XC60T8AWD,0,법인,법인
240046,2021-12,2021,12,Maserati,XC90B6AWD,0,법인,법인
240047,2021-12,2021,12,Mercedes-Benz,XC90T8AWD,0,법인,법인

In [7]:
kaida.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240048 entries, 0 to 240047
Data columns (total 8 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   date        240048 non-null  object
 1   year        240048 non-null  int64
 2   month       240048 non-null  int64
 3   brand       240048 non-null  object
 4   model       240048 non-null  object
 5   value       240048 non-null  int64
 6   sales_type  240048 non-null  object
 7   age         240048 non-null  object
dtypes: int64(3), object(5)
memory usage: 14.7+ MB

In [8]:
kaida.isna().sum()

date          0
year          0
month         0
brand         0
model         0
value         0
sales_type    0
age           0
dtype: int64

In [9]:
share = kaida.groupby("brand").size().reset_index(name='count')
share.sort_values('count', ascending=False, inplace=True)

share = kaida.groupby('brand').agg('sum')[['value']].round().reset_index()
share.sort_values('value', ascending=False, inplace=True)
share

            brand   value
1             BMW  298873
16  Mercedes-Benz  222555
0            Audi  160355
14           MINI   59748
18        Porsche   54699
21     Volkswagen   51085
11     Land Rover   46005
5        Chrysler   43762
22          Volvo   41394
8           Honda   37509
7            Ford   36968
20         Toyota   31777
12          Lexus   25336
4       Chevrolet   23103
17        Peugeot   22656
9          Jaguar   18588
3        Cadillac   18577
13        Lincoln   18142
15       Maserati   15593
6         Citroen   10248
2         Bentley    4684
19    Rolls-Royce    3081
10    Lamborghini    1840

In [10]:
from pyecharts import Pie

keys = list(share["brand"].values)
values = list(share["value"].values)

pie = Pie("브랜드별 점유율")
pie.add("", keys, values, is_randome=True, radius=[50, 80], rosetype='radius', is_legend_show=False,
       is_label_show=True)

pie

- 'kaida'자료를 바탕으로 마켓쉐어를 본 결과 'BMW'가 23.98%로 점유율 1위, Mercedes-Benz가 17.85%로 2위, Audi가 12.86%로 3위

In [11]:
tv_daily = pd.read_csv("datas/TV_daily.csv")
tv_daily

,Year,Month,Day,Date,Advertiser,Product,Channel,Genre,Program,Daypart,CM_Position,Target_Audience,Population,Samples,Spot,Adience,GRP
0,2021,5월,1,2021-05-01,한국토요타자동차,한국토요타렉서스ES300H,TV CHOSUN,토크쇼,강적들,"22:00:00 - 22:59:59 (월,화,?",후CM,개인,24101690,4107,1,95667,0.4
1,2021,5월,1,2021-05-01,한국토요타자동차,한국토요타렉서스ES300H,TV CHOSUN,토크쇼,강적들,"22:00:00 - 22:59:59 (월,화,?",후CM,여20대,1685957,288,1,0,0.0
2,2021,5월,1,2021-05-01,한국토요타자동차,한국토요타렉서스ES300H,TV CHOSUN,토크쇼,강적들,"22:00:00 - 22:59:59 (월,화,?",후CM,여30대,1809949,218,1,0,0.0
3,2021,5월,1,2021-05-01,한국토요타자동차,한국토요타렉서스ES300H,TV CHOSUN,토크쇼,강적들,"22:00:00 - 22:59:59 (월,화,?",후CM,여40대,2047161,318,1,0,0.0
4,2021,5월,1,2021-05-01,한국토요타자동차,한국토요타렉서스ES300H,TV CHOSUN,토크쇼,강적들,"22:00:00 - 22:59:59 (월,화,?",후CM,여50대,2057360,454,1,958,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5810928,2016,6월,30,2016-06-30 00:00:00,FMK,FMK마세라티,MBC SPORTS+,국제,2016메이저리그<생>,"13:00:00 - 13:59:59 (월,화,?",중CM,남20대,1744911,257,1,0,0.0
5810929,2016,6월,30,2016-06-30 00:00:00,FMK,FMK마세라티,MBC SPORTS+,국제,2016메이저리그<생>,"13:00:00 - 13:59:59 (월,화,?",중CM,남30대,2082918,216,1,12451,0.6
5810930,2016,6월,30,2016-06-30 00:00:00,FMK,FMK마세라티,MBC SPORTS+,국제,2016메이저리그<생>,"13:00:00 - 13:59:59 (월,화,?",중CM,남40대,2058605,355,1,29976,1.5
5810931,2016,6월,30,2016-06-30 00:00:00,FMK,FMK마세라티,MBC SPORTS+,국제,2016메이저리그<생>,"13:00:00 - 13:59:59 (월,화,?",중CM,남50대,1536438,389,1,21516,1.4
5810932,2016,6월,30,2016-06-30 00:00:00,FMK,FMK마세라티,MBC SPORTS+,국제,2016메이저리그<생>,"13:00:00 - 13:59:59 (월,화,?",중CM,남60대이상,1379850,449,1,8078,0.6

In [12]:
tv_daily.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5810933 entries, 0 to 5810932
Data columns (total 17 columns):
 #   Column           Dtype
---  ------           -----
 0   Year             int64
 1   Month            object
 2   Day              int64
 3   Date             object
 4   Advertiser       object
 5   Product          object
 6   Channel          object
 7   Genre            object
 8   Program          object
 9   Daypart          object
 10  CM_Position      object
 11  Target_Audience  object
 12  Population       int64
 13  Samples          int64
 14  Spot             int64
 15  Adience          int64
 16  GRP              float64
dtypes: float64(1), int64(6), object(10)
memory usage: 753.7+ MB

In [13]:
tv_daily['Month'] = tv_daily['Month'].str.replace('월','')
tv_daily['Month'] = tv_daily['Month'].astype(int)
tv_daily['Date'] = tv_daily['Date'].str.replace('00:00:00','')
tv_daily['Month'] = pd.to_datetime(tv_daily['Month'], format="%m", errors='raise')

tv_daily['Month'] = tv_daily["Month"].dt.month
tv_daily.sort_values(["Year", "Month"], inplace=True)

tv_daily = tv_daily[["Date", "Year", "Month", "Day", "Product", "Channel", "Genre", "Program", "Daypart", 
                     "CM_Position", "Target_Audience", "Population", "Samples", "Spot", "Adience",
                    "GRP"]].reset_index()

tv_daily.drop(['index'], axis=1, inplace=True)

tv_daily.head()

,Date,Year,Month,Day,Product,Channel,Genre,Program,Daypart,CM_Position,Target_Audience,Population,Samples,Spot,Adience,GRP
0,2016-01-01,2016,1,1,한국토요타캠리,IB SPORTS,국내아마,2015야구대제전,"04:00:00 - 04:59:59 (월,화,?",중CM,개인,22549820,4033,1,0,0.0
1,2016-01-01,2016,1,1,한국토요타캠리,IB SPORTS,국내아마,2015야구대제전,"04:00:00 - 04:59:59 (월,화,?",중CM,여20대,1717889,255,1,0,0.0
2,2016-01-01,2016,1,1,한국토요타캠리,IB SPORTS,국내아마,2015야구대제전,"04:00:00 - 04:59:59 (월,화,?",중CM,여30대,2063861,249,1,0,0.0
3,2016-01-01,2016,1,1,한국토요타캠리,IB SPORTS,국내아마,2015야구대제전,"04:00:00 - 04:59:59 (월,화,?",중CM,여40대,2063925,387,1,0,0.0
4,2016-01-01,2016,1,1,한국토요타캠리,IB SPORTS,국내아마,2015야구대제전,"04:00:00 - 04:59:59 (월,화,?",중CM,여50대,1572971,382,1,0,0.0

In [14]:
tv_daily.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5810933 entries, 0 to 5810932
Data columns (total 16 columns):
 #   Column           Dtype
---  ------           -----
 0   Date             object
 1   Year             int64
 2   Month            int64
 3   Day              int64
 4   Product          object
 5   Channel          object
 6   Genre            object
 7   Program          object
 8   Daypart          object
 9   CM_Position      object
 10  Target_Audience  object
 11  Population       int64
 12  Samples          int64
 13  Spot             int64
 14  Adience          int64
 15  GRP              float64
dtypes: float64(1), int64(7), object(8)
memory usage: 709.3+ MB

In [15]:
# 결측치 확인 : 없음
tv_daily.isna().sum()

Date               0
Year               0
Month              0
Day                0
Product            0
Channel            0
Genre              0
Program            0
Daypart            0
CM_Position        0
Target_Audience    0
Population         0
Samples            0
Spot               0
Adience            0
GRP                0
dtype: int64

In [16]:
grp = tv_daily.groupby("Product").size().reset_index(name='count')
grp.sort_values('count', ascending=False, inplace=True)

grp = tv_daily.groupby('Product').agg('sum')[['GRP']].round().reset_index()
grp.sort_values('GRP', ascending=False, inplace=True)
grp

         Product      GRP
109      포드익스플로러  41264.0
137  한국토요타자동차렉서스  33377.0
54         볼보S90  33352.0
52           볼보*  26859.0
101      크라이슬러지프  26408.0
..           ...      ...
59         비워크지프     70.0
119   한국토요타GR수프라     52.0
88    재규어랜드로버디펜더     35.0
6          BMWX5     34.0
107      포드링컨MKZ      0.0

[161 rows x 2 columns]

In [17]:
keys = list(grp["Product"].values)
values = list(grp["GRP"].values)

pie = Pie("Product별 GRP ")
pie.add("", keys, values, is_randome=True, radius=[35, 65], is_legend_show=False,
       is_label_show=True)

pie

In [18]:
keys = list(grp["Product"][:20].values)
values = list(grp["GRP"][:20].values)

pie = Pie("Product별 GRP Top10 ")
pie.add("", keys, values, is_randome=True, radius=[40, 75], is_legend_show=False, 
        rosetype='radius', is_label_show=True)

pie

In [19]:
ch = tv_daily.groupby(by=["Year"]).sum().round(0).reset_index()
ch

,Year,Month,Day,Population,Samples,Spot,Adience,GRP
0,2016,4390518,12016983,2752230023881,518278258,819533,5970624267,176158.0
1,2017,9739433,22378587,5448410997374,936517007,1503744,7972956097,209772.0
2,2018,8119384,21815659,5312210479611,903539364,1429699,9309013185,240931.0
3,2019,5608933,16452876,4069794793954,703860856,1139248,8085144441,207546.0
4,2020,7528521,16806878,4087870379621,711395529,1116137,8750182052,220409.0
5,2021,915123,4218621,1129768359947,195427779,302533,1952411347,48315.0

In [20]:
from pyecharts import Bar

attr = list(ch["Year"].values)
v1 = list(ch["GRP"].values)

bar = Bar("연도별 GRP 현황")
bar.add("", attr, v1, label_color=['rgba(0,0,0,0)'], is_stack=True)
bar.add("", attr, v1, is_label_show=True, is_stack=True, label_pos='inside')

bar.height = 600
bar.width = 1200

bar

- 2016년 부터 2018년도까지 GRP(광고 캠페인 누적 시청률)가 늘어났다가 2019년도 부터 줄어들었음. 
- 하지만 2019년도에 다시 증가하였음.

In [21]:
ch_grp = tv_daily.groupby("Channel").size().reset_index(name='count')
ch_grp.sort_values('count', ascending=False, inplace=True)

ch_grp = tv_daily.groupby('Channel').agg('sum')[['GRP']].round(0).reset_index()
ch_grp.sort_values('GRP', ascending=False, inplace=True)
ch_grp

        Channel       GRP
43          SBS  197402.0
10         JTBC  189519.0
67          tvN  136204.0
25          MBC  100006.0
35          OCN   53793.0
..          ...       ...
47      SBS MTV       1.0
17     KBS Kids       0.0
20    KBSN Life       0.0
34  Nickelodeon       0.0
18        KBS W       0.0

[81 rows x 2 columns]

In [22]:
from pyecharts import Bar

attr = list(ch_grp["Channel"][:10].values)
v1 = list(ch_grp["GRP"][:10].values)

bar = Bar("채널별 GRP")
bar.add("", attr, v1, is_stack=True, is_label_show=True, label_pos='inside', 
        label_color=['#4C82B4'], legend_pos='right')

bar.height = 600
bar.width = 1200

bar

- GRP가 가장 높은 채널은 197,402로 SBS

In [23]:
age = tv_daily.groupby("Target_Audience").size().reset_index(name='count')
age.sort_values('count', ascending=False, inplace=True)

age = tv_daily.groupby('Target_Audience').agg('sum')[['GRP']].round().reset_index()
age.sort_values('GRP', ascending=False, inplace=True)

# 연령대 중 "개인" 제거
age = age.drop([0])
age.reset_index(drop=True, inplace=True)

age

  Target_Audience       GRP
0            여50대  158402.0
1            여40대  146769.0
2          남60대이상  127015.0
3            남50대  125430.0
4          여60대이상  123950.0
5            남40대  111432.0
6            여30대   85642.0
7            남30대   56460.0
8            여20대   44190.0
9            남20대   33028.0

In [24]:
from pyecharts import Funnel

attr = list(age["Target_Audience"].values)
value = list(age["GRP"].values)

funnel = Funnel("연령별 GRP")
funnel.add("", attr, value, is_label_show=True, label_pos="inside", label_text_color="#fff")

funnel.height = 600
funnel.width = 1200

funnel

In [25]:
ch_age = pd.pivot_table(tv_daily, index=['Target_Audience', 'Channel'], 
                      aggfunc={'Population':'mean', 'Samples':'mean', 'Spot':'mean', 'GRP':sum 
                               }).round().reset_index()
ch_age

    Target_Audience    Channel    GRP  Population  Samples  Spot
0                개인    CH view   23.0  23867490.0   4079.0   1.0
1                개인  Discovery    5.0  24042088.0   4130.0   1.0
2                개인     Dramax   38.0  23531370.0   4143.0   1.0
3                개인        EBS  170.0  23582815.0   4125.0   1.0
4                개인        E채널   58.0  23750453.0   4073.0   1.0
..              ...        ...    ...         ...      ...   ...
886          여60대이상     채널A플러스    5.0   2006849.0    474.0   1.0
887          여60대이상      코미디TV   50.0   2532369.0    530.0   1.0
888          여60대이상       큐브TV    0.0   2542611.0    535.0   1.0
889          여60대이상     한국경제TV    6.0   2758563.0    557.0   1.0
890          여60대이상       히스토리    1.0   2479523.0    526.0   1.0

[891 rows x 6 columns]

In [26]:
ch_age["Target_Audience"].unique()

array(['개인', '남20대', '남30대', '남40대', '남50대', '남60대이상', '여20대', '여30대',
       '여40대', '여50대', '여60대이상'], dtype=object)

In [27]:
m_20age = pd.DataFrame(ch_age.loc[(ch_age['Target_Audience'] == '남20대') & (ch_age['Channel'])]) 
m_20age.sort_values('GRP', ascending=False, inplace=True)
m_20age

    Target_Audience      Channel     GRP  Population  Samples  Spot
91             남20대         JTBC  5785.0   1725137.0    248.0   1.0
124            남20대          SBS  5528.0   1733414.0    254.0   1.0
148            남20대          tvN  4240.0   1728258.0    250.0   1.0
106            남20대          MBC  2977.0   1734188.0    255.0   1.0
116            남20대          OCN  1947.0   1725770.0    249.0   1.0
..              ...          ...     ...         ...      ...   ...
115            남20대  Nickelodeon     0.0   1744917.0    241.0   1.0
126            남20대      SBS FIL     0.0   1761025.0    284.0   1.0
128            남20대      SBS MTV     0.0   1744918.0    240.0   1.0
142            남20대   Tooniverse     0.0   1751113.0    274.0   1.0
161            남20대         히스토리     0.0   1736417.0    261.0   1.0

[81 rows x 6 columns]

In [28]:
keys = list(m_20age["Channel"][:20].values)
values = list(m_20age["GRP"][:20].values)

pie = Pie("남자 20대 Chanel GRP")
pie.add("", keys, values, is_randome=True, radius=[40, 75], is_legend_show=False, 
        rosetype='radius', is_label_show=True)

pie

- GRP 기준으로 20대 남자가 선호하는 채널은 18.67%로 JTBC 이다.

In [29]:
ch_age = pd.pivot_table(tv_daily, index=['Target_Audience', 'Channel'], 
                      aggfunc={'Population':'mean', 'Samples':'mean', 'Spot':'mean', 'GRP':sum 
                               }).round().reset_index()

f_20age = pd.DataFrame(ch_age.loc[(ch_age['Target_Audience'] == '여20대') & (ch_age['Channel'])]) 
f_20age.sort_values('GRP', ascending=False, inplace=True)
f_20age

    Target_Audience      Channel     GRP  Population  Samples  Spot
496            여20대         JTBC  7580.0   1652398.0    259.0   1.0
529            여20대          SBS  7459.0   1661760.0    270.0   1.0
553            여20대          tvN  7000.0   1654728.0    262.0   1.0
511            여20대          MBC  4460.0   1662943.0    269.0   1.0
521            여20대          OCN  2400.0   1653725.0    259.0   1.0
..              ...          ...     ...         ...      ...   ...
541            여20대     SPOTV ON     0.0   1685951.0    285.0   1.0
512            여20대        MBC M     0.0   1652129.0    271.0   1.0
520            여20대  Nickelodeon     0.0   1717950.0    274.0   1.0
524            여20대          OGN     0.0   1647058.0    259.0   1.0
566            여20대         히스토리     0.0   1651551.0    281.0   1.0

[81 rows x 6 columns]

In [30]:
keys = list(f_20age["Channel"][:20].values)
values = list(f_20age["GRP"][:20].values)

pie = Pie("여자 20대 Chanel GRP")
pie.add("", keys, values, is_randome=True, radius=[40, 75], is_legend_show=False, 
        rosetype='radius', is_label_show=True)

pie

In [31]:
ch_age = pd.pivot_table(tv_daily, index=['Target_Audience', 'Channel'], 
                      aggfunc={'Population':'mean', 'Samples':'mean', 'Spot':'mean', 'GRP':sum 
                               }).round().reset_index()

m_30age = pd.DataFrame(ch_age.loc[(ch_age['Target_Audience'] == '남30대') & (ch_age['Channel'])]) 
m_30age.sort_values('GRP', ascending=False, inplace=True)
m_30age

    Target_Audience     Channel      GRP  Population  Samples  Spot
172            남30대        JTBC  10972.0   1971295.0    197.0   1.0
205            남30대         SBS   8314.0   1963705.0    201.0   1.0
229            남30대         tvN   7091.0   1964540.0    198.0   1.0
187            남30대         MBC   4509.0   1961645.0    202.0   1.0
197            남30대         OCN   3803.0   1972150.0    197.0   1.0
..              ...         ...      ...         ...      ...   ...
185            남30대         K바둑      0.0   1959578.0    181.0   1.0
182            남30대   KBSN Life      0.0   1993005.0    184.0   1.0
171            남30대   IB SPORTS      0.0   2082838.0    217.0   1.0
222            남30대  TV CHOSUN2      0.0   1912038.0    219.0   1.0
179            남30대    KBS Kids      0.0   2082926.0    204.0   1.0

[81 rows x 6 columns]

In [32]:
keys = list(m_30age["Channel"][:20].values)
values = list(m_30age["GRP"][:20].values)

pie = Pie("남자 30대 Chanel GRP")
pie.add("", keys, values, is_randome=True, radius=[40, 75], is_legend_show=False, 
        rosetype='radius', is_label_show=True)

pie

In [33]:
ch_age = pd.pivot_table(tv_daily, index=['Target_Audience', 'Channel'], 
                      aggfunc={'Population':'mean', 'Samples':'mean', 'Spot':'mean', 'GRP':sum 
                               }).round().reset_index()

f_30age = pd.DataFrame(ch_age.loc[(ch_age['Target_Audience'] == '여30대') & (ch_age['Channel'])]) 
f_30age.sort_values('GRP', ascending=False, inplace=True)
f_30age

    Target_Audience     Channel      GRP  Population  Samples  Spot
634            여30대         tvN  18788.0   1911142.0    206.0   1.0
577            여30대        JTBC  16890.0   1918874.0    206.0   1.0
610            여30대         SBS  13498.0   1910930.0    209.0   1.0
592            여30대         MBC   7767.0   1908144.0    211.0   1.0
602            여30대         OCN   5272.0   1919902.0    205.0   1.0
..              ...         ...      ...         ...      ...   ...
605            여30대         OGN      0.0   1881861.0    206.0   1.0
628            여30대  Tooniverse      0.0   1846616.0    216.0   1.0
627            여30대  TV CHOSUN2      0.0   1846537.0    215.0   1.0
614            여30대     SBS MTV      0.0   2063942.0    238.0   1.0
647            여30대        히스토리      0.0   1869609.0    208.0   1.0

[81 rows x 6 columns]

In [34]:
keys = list(f_30age["Channel"][:20].values)
values = list(f_30age["GRP"][:20].values)

pie = Pie("여자 30대 Chanel GRP")
pie.add("", keys, values, is_randome=True, radius=[40, 75], is_legend_show=False, 
        rosetype='radius', is_label_show=True)

pie

In [35]:
ch_age = pd.pivot_table(tv_daily, index=['Target_Audience', 'Channel'], 
                      aggfunc={'Population':'mean', 'Samples':'mean', 'Spot':'mean', 'GRP':sum 
                               }).round().reset_index()

m_40age = pd.DataFrame(ch_age.loc[(ch_age['Target_Audience'] == '남40대') & (ch_age['Channel'])]) 
m_40age.sort_values('GRP', ascending=False, inplace=True)
m_40age

    Target_Audience      Channel      GRP  Population  Samples  Spot
286            남40대          SBS  20682.0   2114217.0    301.0   1.0
253            남40대         JTBC  18601.0   2123805.0    301.0   1.0
310            남40대          tvN  14134.0   2121174.0    299.0   1.0
268            남40대          MBC   9658.0   2110932.0    299.0   1.0
278            남40대          OCN   8210.0   2122249.0    301.0   1.0
..              ...          ...      ...         ...      ...   ...
277            남40대  Nickelodeon      0.0   2058618.0    354.0   1.0
303            남40대   TV CHOSUN2      0.0   2098496.0    268.0   1.0
263            남40대    KBSN Life      0.0   2161438.0    294.0   1.0
322            남40대       한국경제TV      0.0   2076823.0    278.0   1.0
290            남40대      SBS MTV      0.0   2058617.0    354.0   1.0

[81 rows x 6 columns]

In [36]:
keys = list(m_40age["Channel"][:20].values)
values = list(m_40age["GRP"][:20].values)

pie = Pie("남자 40대 Chanel GRP")
pie.add("", keys, values, is_randome=True, radius=[40, 75], is_legend_show=False, 
        rosetype='radius', is_label_show=True)

pie

In [37]:
ch_age = pd.pivot_table(tv_daily, index=['Target_Audience', 'Channel'], 
                      aggfunc={'Population':'mean', 'Samples':'mean', 'Spot':'mean', 'GRP':sum 
                               }).round().reset_index()

f_40age = pd.DataFrame(ch_age.loc[(ch_age['Target_Audience'] == '여40대') & (ch_age['Channel'])]) 
f_40age.sort_values('GRP', ascending=False, inplace=True)
f_40age

    Target_Audience      Channel      GRP  Population  Samples  Spot
658            여40대         JTBC  28757.0   2109724.0    369.0   1.0
691            여40대          SBS  28046.0   2099624.0    363.0   1.0
715            여40대          tvN  26209.0   2106569.0    365.0   1.0
673            여40대          MBC  13234.0   2095694.0    362.0   1.0
683            여40대          OCN   8936.0   2108122.0    368.0   1.0
..              ...          ...      ...         ...      ...   ...
708            여40대   TV CHOSUN2      0.0   2072943.0    320.0   1.0
672            여40대       Life U      0.0   2115234.0    347.0   1.0
704            여40대    SPOTV ON2      0.0   2047158.0    321.0   1.0
682            여40대  Nickelodeon      0.0   2064010.0    421.0   1.0
728            여40대         히스토리      0.0   2115235.0    347.0   1.0

[81 rows x 6 columns]

In [38]:
keys = list(f_40age["Channel"][:20].values)
values = list(f_40age["GRP"][:20].values)

pie = Pie("여자 40대 Chanel GRP")
pie.add("", keys, values, is_randome=True, radius=[40, 75], is_legend_show=False, 
        rosetype='radius', is_label_show=True)

pie

In [39]:
ch_age = pd.pivot_table(tv_daily, index=['Target_Audience', 'Channel'], 
                      aggfunc={'Population':'mean', 'Samples':'mean', 'Spot':'mean', 'GRP':sum 
                               }).round().reset_index()

m_50age = pd.DataFrame(ch_age.loc[(ch_age['Target_Audience'] == '남50대') & (ch_age['Channel'])]) 
m_50age.sort_values('GRP', ascending=False, inplace=True)
m_50age

    Target_Audience      Channel      GRP  Population  Samples  Spot
367            남50대          SBS  22472.0   1900264.0    387.0   1.0
334            남50대         JTBC  21037.0   1904239.0    386.0   1.0
349            남50대          MBC  10722.0   1905173.0    386.0   1.0
391            남50대          tvN  10227.0   1913041.0    386.0   1.0
352            남50대  MBC SPORTS+   9738.0   1858351.0    388.0   1.0
..              ...          ...      ...         ...      ...   ...
344            남50대    KBSN Life      0.0   1936195.0    388.0   1.0
398            남50대       채널 다이아      0.0   1989336.0    392.0   1.0
358            남50대  Nickelodeon      0.0   1536447.0    367.0   1.0
371            남50대      SBS MTV      0.0   1536446.0    366.0   1.0
341            남50대     KBS Kids      0.0   1536435.0    371.0   1.0

[81 rows x 6 columns]

In [40]:
keys = list(m_50age["Channel"][:20].values)
values = list(m_50age["GRP"][:20].values)

pie = Pie("남자 50대 Chanel GRP")
pie.add("", keys, values, is_randome=True, radius=[40, 75], is_legend_show=False, 
        rosetype='radius', is_label_show=True)

pie

In [41]:
ch_age = pd.pivot_table(tv_daily, index=['Target_Audience', 'Channel'], 
                      aggfunc={'Population':'mean', 'Samples':'mean', 'Spot':'mean', 'GRP':sum 
                               }).round().reset_index()

f_50age = pd.DataFrame(ch_age.loc[(ch_age['Target_Audience'] == '여50대') & (ch_age['Channel'])]) 
f_50age.sort_values('GRP', ascending=False, inplace=True)
f_50age

    Target_Audience     Channel      GRP  Population  Samples  Spot
772            여50대         SBS  30643.0   1916251.0    431.0   1.0
739            여50대        JTBC  29377.0   1917082.0    428.0   1.0
796            여50대         tvN  19578.0   1926475.0    429.0   1.0
754            여50대         MBC  14944.0   1921969.0    430.0   1.0
748            여50대        KBS2   7650.0   1911139.0    434.0   1.0
..              ...         ...      ...         ...      ...   ...
738            여50대   IB SPORTS      0.0   1572969.0    384.0   1.0
789            여50대  TV CHOSUN2      0.0   2026770.0    448.0   1.0
746            여50대    KBS Kids      0.0   1573028.0    407.0   1.0
790            여50대  Tooniverse      0.0   2026850.0    442.0   1.0
747            여50대       KBS W      0.0   1940069.0    428.0   1.0

[81 rows x 6 columns]

In [42]:
keys = list(m_50age["Channel"][:20].values)
values = list(m_50age["GRP"][:20].values)

pie = Pie("여자 50대 Chanel GRP")
pie.add("", keys, values, is_randome=True, radius=[40, 75], is_legend_show=False, 
        rosetype='radius', is_label_show=True)

pie

In [43]:
ch_age = pd.pivot_table(tv_daily, index=['Target_Audience', 'Channel'], 
                      aggfunc={'Population':'mean', 'Samples':'mean', 'Spot':'mean', 'GRP':sum 
                               }).round().reset_index()

m_60age = pd.DataFrame(ch_age.loc[(ch_age['Target_Audience'] == '남60대이상') & (ch_age['Channel'])]) 
m_60age.sort_values('GRP', ascending=False, inplace=True)
m_60age

    Target_Audience      Channel      GRP  Population  Samples  Spot
448          남60대이상          SBS  20850.0   1923472.0    517.0   1.0
415          남60대이상         JTBC  14306.0   1893714.0    518.0   1.0
433          남60대이상  MBC SPORTS+  11066.0   1833474.0    507.0   1.0
430          남60대이상          MBC  10408.0   1938083.0    520.0   1.0
436          남60대이상          MBN   7085.0   1922285.0    520.0   1.0
..              ...          ...      ...         ...      ...   ...
452          남60대이상      SBS MTV      0.0   1379845.0    426.0   1.0
414          남60대이상    IB SPORTS      0.0   1379794.0    429.0   1.0
466          남60대이상   Tooniverse      0.0   2176493.0    566.0   1.0
483          남60대이상         큐브TV      0.0   2110537.0    542.0   1.0
439          남60대이상  Nickelodeon      0.0   1379844.0    426.0   1.0

[81 rows x 6 columns]

In [44]:
keys = list(m_60age["Channel"][:20].values)
values = list(m_60age["GRP"][:20].values)

pie = Pie("남자 60대 Chanel GRP")
pie.add("", keys, values, is_randome=True, radius=[40, 75], is_legend_show=False, 
        rosetype='radius', is_label_show=True)

pie

In [45]:
ch_age = pd.pivot_table(tv_daily, index=['Target_Audience', 'Channel'], 
                      aggfunc={'Population':'mean', 'Samples':'mean', 'Spot':'mean', 'GRP':sum 
                               }).round().reset_index()

f_60age = pd.DataFrame(ch_age.loc[(ch_age['Target_Audience'] == '여60대이상') & (ch_age['Channel'])]) 
f_60age.sort_values('GRP', ascending=False, inplace=True)
f_60age

    Target_Audience      Channel      GRP  Population  Samples  Spot
853          여60대이상          SBS  23196.0   2343212.0    512.0   1.0
820          여60대이상         JTBC  20210.0   2311609.0    514.0   1.0
835          여60대이상          MBC  12926.0   2358789.0    514.0   1.0
877          여60대이상          tvN  11258.0   2341556.0    516.0   1.0
829          여60대이상         KBS2   8847.0   2354911.0    512.0   1.0
..              ...          ...      ...         ...      ...   ...
844          여60대이상  Nickelodeon      0.0   1761882.0    425.0   1.0
848          여60대이상          OGN      0.0   2458135.0    529.0   1.0
888          여60대이상         큐브TV      0.0   2542611.0    535.0   1.0
857          여60대이상      SBS MTV      0.0   1761881.0    425.0   1.0
827          여60대이상     KBS Kids      0.0   1761878.0    421.0   1.0

[81 rows x 6 columns]

In [46]:
keys = list(f_60age["Channel"][:20].values)
values = list(f_60age["GRP"][:20].values)

pie = Pie("여자 60대 Chanel GRP")
pie.add("", keys, values, is_randome=True, radius=[40, 75], is_legend_show=False, 
        rosetype='radius', is_label_show=True)

pie

In [47]:
before = pd.pivot_table(tv_daily, index=['Genre', 'CM_Position', "Target_Audience", "Channel", "Program"], 
                      aggfunc={'Population':sum, 'Samples':'mean', 'Spot':sum, 'GRP':sum 
                               }).round().reset_index()

before = pd.DataFrame(before.loc[(before['CM_Position'] == '전CM') & (before["Genre"])]) 
before.sort_values('GRP', ascending=False, inplace=True)
before.reset_index(drop=True, inplace=True)
before.head(10)

,Genre,CM_Position,Target_Audience,Channel,Program,GRP,Population,Samples,Spot
0,종합,전CM,여50대,SBS,SBS8뉴스,3045.0,2049083026,429.0,1083
1,종합,전CM,여40대,SBS,SBS8뉴스,2818.0,2236047638,362.0,1083
2,종합,전CM,여60대이상,SBS,SBS8뉴스,2422.0,2502220308,516.0,1083
3,종합,전CM,남50대,SBS,SBS8뉴스,2173.0,2032906093,386.0,1083
4,종합,전CM,남60대이상,SBS,SBS8뉴스,2167.0,2055028893,522.0,1083
5,종합,전CM,남40대,SBS,SBS8뉴스,2155.0,2252558495,298.0,1083
6,종합,전CM,개인,SBS,SBS8뉴스,1697.0,25087805923,4088.0,1083
7,종합,전CM,여30대,SBS,SBS8뉴스,1527.0,2031371011,208.0,1083
8,종합,전CM,여40대,JTBC,JTBC뉴스룸,1443.0,3247189257,374.0,1550
9,종합,전CM,남50대,JTBC,JTBC뉴스룸,1423.0,2883887262,387.0,1550

In [48]:
mid = pd.pivot_table(tv_daily, index=['Genre', 'CM_Position', "Target_Audience", "Channel", "Program"], 
                      aggfunc={'Population':sum, 'Samples':'mean', 'Spot':sum, 'GRP':sum 
                               }).round().reset_index()

mid = pd.DataFrame(mid.loc[(mid['CM_Position'] == '중CM') & (mid["Genre"])]) 
mid.sort_values('GRP', ascending=False, inplace=True)
mid.reset_index(drop=True, inplace=True)
mid.head(10)

,Genre,CM_Position,Target_Audience,Channel,Program,GRP,Population,Samples,Spot
0,국제,중CM,남60대이상,MBC SPORTS+,2016메이저리그<생>,1552.0,1658580232,442.0,1907
1,국제,중CM,남50대,MBC SPORTS+,2016메이저리그<생>,1404.0,1846807320,380.0,1907
2,국제,중CM,남50대,MBC SPORTS+,2019메이저리그<생>,1033.0,2037959702,396.0,1285
3,국제,중CM,남60대이상,MBC SPORTS+,2019메이저리그<생>,800.0,2112460745,521.0,1285
4,종합,중CM,남50대,JTBC,JTBC뉴스룸,778.0,351878585,391.0,179
5,종합,중CM,여50대,JTBC,JTBC뉴스룸,764.0,353830539,437.0,179
6,국제,중CM,남40대,MBC SPORTS+,2016메이저리그<생>,708.0,2474464091,351.0,1907
7,종합,중CM,여40대,JTBC,JTBC뉴스룸,664.0,375527126,354.0,179
8,국제,중CM,여50대,MBC SPORTS+,2016메이저리그<생>,661.0,1890778923,414.0,1907
9,오락기타,중CM,여30대,JTBC,아는형님,616.0,290055091,205.0,155

In [49]:
after = pd.pivot_table(tv_daily, index=['Genre', 'CM_Position', "Target_Audience", "Channel", "Program"], 
                      aggfunc={'Population':'mean', 'Samples':'mean', 'Spot':sum, 'GRP':sum 
                               }).round().reset_index()

after = pd.DataFrame(after.loc[(after['CM_Position'] == '후CM') & (after["Genre"])]) 
after.sort_values('GRP', ascending=False, inplace=True)
after.reset_index(drop=True, inplace=True)
after.head(10)

,Genre,CM_Position,Target_Audience,Channel,Program,GRP,Population,Samples,Spot
0,종합,후CM,여50대,SBS,SBS8뉴스L,4865.0,1883829.0,433.0,1237
1,종합,후CM,여40대,SBS,SBS8뉴스L,4394.0,2099661.0,369.0,1237
2,종합,후CM,여50대,JTBC,JTBC뉴스룸,4364.0,1923179.0,430.0,2192
3,종합,후CM,남60대이상,SBS,SBS8뉴스L,4360.0,1868112.0,508.0,1237
4,종합,후CM,여40대,JTBC,JTBC뉴스룸,4261.0,2110221.0,368.0,2192
5,종합,후CM,남50대,SBS,SBS8뉴스L,4252.0,1866761.0,389.0,1237
6,종합,후CM,남50대,JTBC,JTBC뉴스룸,3828.0,1910981.0,386.0,2192
7,종합,후CM,남40대,SBS,SBS8뉴스L,3538.0,2112026.0,309.0,1237
8,종합,후CM,여60대이상,SBS,SBS8뉴스L,3149.0,2284010.0,504.0,1237
9,종합,후CM,남40대,JTBC,JTBC뉴스룸,2972.0,2124069.0,301.0,2192

In [50]:
age_product = pd.pivot_table(tv_daily, index=['Target_Audience', 'Product', "Channel"], 
                      aggfunc={'Population':'mean', 'Samples':'mean', 'Spot':sum, 'GRP':sum 
                               }).round().reset_index()

age_product = pd.DataFrame(age_product.loc[(age_product['Target_Audience']=="남20대")])
age_product.sort_values('GRP', ascending=False, inplace=True)
age_product.head(20)

,Target_Audience,Product,Channel,GRP,Population,Samples,Spot
2326,남20대,볼보*,MBC,295.0,1739983.0,262.0,469
2357,남20대,볼보S90,MBC,241.0,1751088.0,277.0,477
1948,남20대,BMW미니컨트리맨,JTBC,232.0,1701996.0,240.0,1080
3405,남20대,한국토요타자동차렉서스,JTBC,222.0,1705910.0,242.0,1044
2329,남20대,볼보*,SBS,217.0,1746948.0,268.0,311
2360,남20대,볼보S90,SBS,216.0,1750381.0,273.0,459
2678,남20대,재규어E-PACE,SBS,214.0,1712210.0,238.0,549
2651,남20대,아우디폭스바겐티구안,SBS,211.0,1728334.0,252.0,389
2880,남20대,크라이슬러지프,JTBC,206.0,1709244.0,237.0,812
2242,남20대,메르세데스벤츠,SBS,205.0,1737142.0,264.0,177
2356,남20대,볼보S90,KBS2,202.0,1751084.0,277.0,326
2614,남20대,아우디코리아아우디,SBS,201.0,1728278.0,257.0,364
2992,남20대,포드익스플로러,JTBC,200.0,1726536.0,252.0,1271
3003,남20대,포드익스플로러,MBC SPORTS+,190.0,1725600.0,252.0,2306
2889,남20대,크라이슬러지프,SBS,189.0,1738926.0,260.0,313
2403,남20대,볼보XC90,JTBC,188.0,1736999.0,257.0,1339
2281,남20대,벤츠E클래스,SBS,188.0,1738762.0,262.0,416
2907,남20대,크라이슬러지프랭글러,SBS,166.0,1728669.0,251.0,287
2214,남20대,링컨컨티넨탈,JTBC,165.0,1716461.0,244.0,655
2745,남20대,재규어랜드로버디스커버리스포츠,SBS,164.0,1750717.0,269.0,225

In [51]:
age_product = pd.pivot_table(tv_daily, index=['Target_Audience', 'Product', "Channel"], 
                      aggfunc={'Population':'mean', 'Samples':'mean', 'Spot':sum, 'GRP':sum 
                               }).round().reset_index()

age_product = pd.DataFrame(age_product.loc[(age_product['Target_Audience']=="여20대")])
age_product.sort_values('GRP', ascending=False, inplace=True)
age_product.head(20)

,Target_Audience,Product,Channel,GRP,Population,Samples,Spot
11466,여20대,볼보*,MBC,406.0,1660735.0,268.0,469
11818,여20대,재규어E-PACE,SBS,379.0,1631428.0,246.0,549
11421,여20대,벤츠E클래스,SBS,322.0,1665876.0,281.0,416
11754,여20대,아우디코리아아우디,SBS,291.0,1654709.0,265.0,364
11543,여20대,볼보XC90,JTBC,288.0,1661247.0,281.0,1339
11500,여20대,볼보S90,SBS,284.0,1676024.0,295.0,459
12545,여20대,한국토요타자동차렉서스,JTBC,275.0,1626408.0,246.0,1044
12029,여20대,크라이슬러지프,SBS,271.0,1654784.0,281.0,313
11088,여20대,BMW미니컨트리맨,JTBC,266.0,1622699.0,240.0,1080
12132,여20대,포드익스플로러,JTBC,254.0,1646062.0,260.0,1271
12047,여20대,크라이슬러지프랭글러,SBS,244.0,1645111.0,270.0,287
11354,여20대,링컨컨티넨탈,JTBC,242.0,1652218.0,253.0,655
11979,여20대,캐딜락CT6,tvN,242.0,1642587.0,264.0,1137
11911,여20대,재규어랜드로버레인지로버이보크,SBS,241.0,1651662.0,283.0,395
11497,여20대,볼보S90,MBC,237.0,1670345.0,298.0,477
11791,여20대,아우디폭스바겐티구안,SBS,235.0,1645721.0,268.0,389
12020,여20대,크라이슬러지프,JTBC,234.0,1628583.0,236.0,812
12282,여20대,한국토요타렉서스ES300H,JTBC,232.0,1639389.0,250.0,805
11382,여20대,메르세데스벤츠,SBS,230.0,1654711.0,284.0,177
12615,여20대,한국토요타프리우스,JTBC,230.0,1672610.0,262.0,804

In [ ]:
tv_mon

In [ ]:
def aud_ABC(brand, year=2020):
    import matplotlib as mpl
    mpl.use('TKAgg')
    import matplotlib.pyplot as plt
    
    aud_df_pv = making_aud_df(brand, year)
    aud_df_pv = aud_df_pv.sort_values(by='GRP', ascending=False)
    aud_df_pv['GRP_per'] = [g/sum(aud_df_pv['GRP'])*100 for g in aud_df_pv['GRP']]
    aud_df_pv['GRP_per_cum'] = [sum(aud_df_pv['GRP_per'].iloc[:i+1]) for i in range(len(aud_df_pv))]
    
    fig, ax1 = plt.subplots(figsize=(10,6))
    sns.set_style("white")
    ax1.set_title('ABC analysis of Audiences', fontsize=20)
    x = aud_df_pv['Target_Audience'].to_list()
    y = aud_df_pv['GRP_per'].to_list()
    y_cum = aud_df_pv['GRP_per_cum'].to_list()

    ax1.set_ylabel('Composition ratio %',fontsize=13)
    ax1 = sns.barplot(x, y, palette='summer')

    ax1.tick_params(axis='y')
    ax2 = ax1.twinx()
    color = 'tab:red'
    ax2.set_ylabel('Cumulative composition ratio %',fontsize=13)
    sns.lineplot(x, y_cum, color='red')
    ax2.tick_params(axis='y')
    
    fig.show()